### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by franciscoGPS** [crystal-data/num.cr#70]
Hi Chris. Awesome shard. Thanks for your amazing work in num. 

#### Problem description
![image](https://user-images.githubusercontent.com/6760672/139604732-292fd0f5-789e-42da-8448-8a1f6d6c13de.png)

There is an error when running either shards install or shards update. As far as I see is that there's a version mismatch between the github version vs what it is on the shard.yml.

Thanks in advance for your support. 
![image](https://user-images.githubusercontent.com/6760672/139604698-6b5e23ad-2081-4ba2-8380-6abf1c2c8d83.png)

![image](https://user-images.githubusercontent.com/6760672/139604682-49e1d65c-d88e-486c-8c64-f34695679269.png)

**Comment by christopherzimmerman** [comment]
@franciscoGPS Thanks for the issue.  The error you're running into is because you don't have `clang` installed (required to build some small C-extensions for the shard), the version should only raise a warning.  If you don't want to install it, you can probably use `--skip-postinstall` when you run `shards install`, and be able to use pretty much everything except kmeans from `Num.cr`.  I am bumping the version on master to fix the warning though.
